apiVersion: v1
kind: Service
metadata:
  name: student-portal-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: student-portal-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
